### ISSUE TITLE
Evaluation Code

### ISSUE THREAD

**Issue by kayson-tihoi** [yztang4/WarpingGAN#2]
Hi,

Thanks for your nice work on Point Cloud Generation!

Any plan to release your code for evaluation?

Best.

**Comment by yztang4** [comment]
Hi, thanks for your comment. 
For the evaluation, you can use your own evaluation code and your own setting.

**Comment by yztang4** [comment]
> Hi,
> 
> Thanks for your nice work on Point Cloud Generation!
> 
> Any plan to release your code for evaluation?
> 
> Best.

Hi, thanks for your comment.
For the evaluation, you can use your own evaluation code and your own setting.
