### ISSUE TITLE
About Inference and the pre-trained models

### ISSUE THREAD

**Issue by PraveenKumar-Rajendran** [yztang4/WarpingGAN#4]
Hi @yztang4 :)
Thanks for the excellent work! 
Can you please provide your pretrained models with the inference instruction?

Thank you very much!

**Comment by yztang4** [comment]
You can download the generated samples here: [https://drive.google.com/file/d/1YwxoyiWLJC4gxVgZ-ntijo9NQEC0MRlW/view](url)
