### ISSUE TITLE
equest code for evaluation

### ISSUE THREAD

**Issue by wangxin-fighting** [yztang4/WarpingGAN#6]
Hello, excuse me. After carefully reading your paper, I found that the evaluation code is missing. May I ask if it is convenient for you to provide the code for the evaluation? Thank you.

**Comment by yztang4** [comment]
My evaluation code is modified on ShapeGF. You can use their code for evaluation.

**Comment by wangxin-fighting** [comment]
Okay, thank you very much. Wishing you a happy life!
