### ISSUE TITLE
Regarding the generated "ckpt" and "generated" files

### ISSUE THREAD

**Issue by wangxin-fighting** [yztang4/WarpingGAN#7]
Hello, excuse me. After carefully reading your code, I have some doubts. May I ask how to visualize and convert the generated "ckpt" and "generated" files into commonly used formats for point clouds, such as txt.

Looking forward to your answer very much, thank you!

**Comment by yztang4** [comment]
1. load ckpt with torch.load
2. convert the data to numpy format
3. convert numpy to ply or txt, like this [https://stackoverflow.com/questions/62948421/how-to-create-point-cloud-file-ply-from-vertices-stored-as-numpy-array](https://stackoverflow.com/questions/62948421/how-to-create-point-cloud-file-ply-from-vertices-stored-as-numpy-array).

**Comment by yztang4** [comment]
go to the "generated" folder, there should be files like "pc_epochxxx.pt". You can load them with torch.load like 
PC = torch.load("pc_epochxxx.pt").numpy() and then convert them to ply files. the "ckpt" folder saves the weights of WarpingGAN and it cannot be converted to point clouds.

**Comment by wangxin-fighting** [comment]
@yztang4 Firstly, thank you very much for your previous answer, but the link you provided is: https://github.com/yztang4/WarpingGAN/issues/url It no longer exists. Can you provide a new link?

**Comment by yztang4** [comment]
![1684823288477](https://github.com/yztang4/WarpingGAN/assets/101309618/109eef1d-64e2-4579-85f9-a6f98d2796da)

**Comment by yztang4** [comment]
The link is good.

**Comment by yztang4** [comment]
Try again.

**Comment by wangxin-fighting** [comment]
Yes, I have opened this link and will continue to try according to your solution. Thank you again for your generous answer and wish you a happy life! @ @yztang4

**Comment by yztang4** [comment]
Because they are pre-trained models, the network will continue to train the model instead of training the model from epoch 0.

**Comment by wangxin-fighting** [comment]
Okay, thank you again for your answer! @yztang4
