### ISSUE TITLE
About Generating Other Types of Point Clouds in the Dataset

### ISSUE THREAD

**Issue by wangxin-fighting** [yztang4/WarpingGAN#9]
Hello, I would like to ask you again. If I want to generate other types of point clouds, such as "guitar, bag, phone", what else do I need to do besides modifying the class alias I want to generate? (I'll try it out, the generated point cloud is completely different from the actual shape)

**Comment by yztang4** [comment]
do you have wechat(微信？) we can talk there.

**Comment by yztang4** [comment]
you can send it to my email yztang4-c@my.cityu.edu.hk

**Comment by yztang4** [comment]
![snapshot00](https://github.com/yztang4/WarpingGAN/assets/101309618/705568ce-f771-4f16-99d5-4542efae5ccb)
I can generate guitar, I never tried bag or phone. You may provide more details to me so I can know what is wrong. I think wechat is more convenient.

**Comment by wangxin-fighting** [comment]
@yztang4 Okay, I have sent my WeChat to you via email. Please check it. Thank you
